### PR TITLE
Add 2.12.2 to .travis.yml

### PR DESCRIPTION
**Pull request by macalinao**

### CODE REVIEW

**Comment by milessabin** [comment]
I think you'll need to bump the Scala.js version as well.

**Comment by macalinao** [comment]
good point @milessabin -- fixed! :)

**Comment by milessabin** [comment]
LGTM ... many thanks ... merging :-)

**Comment by milessabin** [comment]
Ahh ... actually, I missed that you hadn't also updated build.sbt ... would you mind doing that as well?

**Comment by macalinao** [comment]
whoops... i'll do that. Should I remove 2.11.1 from .travis.yml as well? I didn't think of this as a version upgrade, just testing to see if tests work under 2.12.2.

**Comment by milessabin** [comment]
Yes please! And would you mind bumping 2.11.x to 2.11.11 everywhere as well? :-)

**Pull request merged**
