### PR TITLE
update cats and scala

### PR DESCRIPTION
**Pull request by kailuowang**
can't upgrade to scala 2.12.4 since macro paradise isn't ready.

### CODE REVIEW

**Comment by milessabin** [comment]
What the problem with macro-paradise?

**Comment by kailuowang** [comment]
We got the same error as @xuwei-k documented here. https://gist.github.com/xuwei-k/7bde52e053d2e013bc23f68c5dafb667

**Comment by milessabin** [comment]
Have you tried to minimize it? What source caused @xuwei-k's error? It doesn't seem to be linked to from the gist ...

**Comment by kailuowang** [comment]
I only tried a little. It happens during the derivation of `Semigroup` and ` SemigoupK`

**Comment by milessabin** [comment]
I'm guessing this is `Lazy` related. Try with the latest shapeless snapshot. I'll be making a new 2.3.x release in the next day or so.

**Comment by kailuowang** [comment]
shapeless snapshot seems working.

**Comment by milessabin** [comment]
Thanks for confirming. I suggest waiting for me to release 2.3.3 ... it'll be a day or two.

**Comment by xuwei-k** [comment]
Sorry, I could not minimize reproduce code. I also used shapeless (scalacheck-shapeless).

**Comment by milessabin** [comment]
@xuwei-k it's most likely an issue with `Lazy` that was exposed by 2.12.4. Most likely fixed in https://github.com/milessabin/shapeless/commit/3188e7dc4102d2bf1be35e050cbd3e3506e5a311. I'd be grateful if you could try your test case with the latest shapeless snapshot and let me know if it fixes the problem.

**Comment by xuwei-k** [comment]
Excellent! I confirmed latest shapeless snapshot fixes the problem 😃

**Comment by milessabin** [comment]
@xuwei-k wonderful! Thanks for the update :-)

Just to clarify a little ... the problem is only with `Cached` not `Lazy`, although the underlying macro implementation is related. Were you working with scalacheck-shapeless?

**Comment by milessabin** [comment]
shapeless-2.3.3 just released; http://milessabin.com/blog/2017/12/31/shapeless-2.3.3.

**Comment by kailuowang** [comment]
@milessabin green now. How about merge and a new release?

**Comment by milessabin** [comment]
LGTM :-)

**Pull request merged**
